import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import { useEffect,useState } from 'react'
import Dummy from '../components/dummy'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [blogs, setBlogs] = useState([])
  // use Effect will run every time because inside this you update the state and the useeffect runs every time when the dom change and the state is the part of the dom
  // when you gave a second argument to useeffect to empty array useeffect will run only once after dom render
  // also you can gave this array to any kind of state or variable when it change useeffect will run  
  useEffect(() => {
    fetch('http://localhost:3000/api/blogs')
    .then((data)=>{
      return data.json();
    }).then((data)=>{
      console.log(data)
      setBlogs(data)
    },[])
    // console.log("abhishek is under the useEffect")
  })
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>
        {`
        .abhi{
          color:red;
        }
          `}
      </style>
      <Script src='/sc.js' strategy="lazyOnload"></Script>
      <main className={styles.main}>
        <Dummy/>
        {/* The image component should contain width,height or layout  */}
        <Image src={'/abhi.png'}  width={222} height={100}/>
        <h1 className={styles.title}>
         Hunting Coder
        </h1>
        <span className='abhi dummy'>Abhishek Developer</span>

        <p className={styles.description}>
         Hunting Coder for the  Awesome Developers
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
