import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import Dummy from '../components/dummy'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>
        {`
        .abhi{
          color:red;
        }
          `}
      </style>
      <Script src='/sc.js' strategy="lazyOnload"></Script>
      <main className={styles.main}>
        <Dummy/>
        <h1 className={styles.title}>
         Hunting Coder
        </h1>
        <span className='abhi dummy'>Abhishek Developer</span>

        <p className={styles.description}>
         Hunting Coder for the  Awesome Developers
        </p>
        <nav>
          <ul className={`${styles.abhi} ${styles.abhi2}`}>
            <Link href='/'><a><li>Home</li></a></Link>
            <Link href='/about'><a><li>About</li></a></Link>
            <Link href='/contact'><a><li>Contact</li></a></Link>
          </ul>
          </nav>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
